#!/bin/sh -e
VERSION="$1"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. '1.0.0')"
    exit 1
fi

echo "Updating Cargo.toml version"
sed -E -i "" "s/version = \"[0-9]+\.[0-9]+\.[0-9]+\"/version = \"$VERSION\"/g" Cargo.toml
cargo build  # update Cargo.lock
git add Cargo.toml Cargo.lock
git commit -m "Version $VERSION"
git push

git tag -a "v$VERSION" -m "v$VERSION"
git push origin "v$VERSION"

gh release create "v$VERSION"
./scripts/upload-macos-arm "$VERSION"
