on: [push]

name: build

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2  # for example testing
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: |
          ./scripts/pre-commit
          ls target/release
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: target/release/libcls_ffi.so
          if-no-files-found: error

  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2  # for example testing
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cross
          cross build --release --target aarch64-unknown-linux-gnu
          ls target/release -alh
          ls target/aarch64-unknown-linux-gnu/release -alh
          cp target/aarch64-unknown-linux-gnu/release/libcls_ffi.so target/aarch64-unknown-linux-gnu/release/libcls_ffi_aarch64.so
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: target/aarch64-unknown-linux-gnu/release/libcls_ffi_aarch64.so
          if-no-files-found: error

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2  # for example testing
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: |
          ./scripts/pre-commit
          ls target/release
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: target/release/libcls_ffi.dylib
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2  # for example testing
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo build --release
          python3 ffi_examples\python.py
          ls target\release
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: target\release\cls_ffi.dll
          if-no-files-found: error

  upload-artifacts:
    needs: [linux, linux-aarch64, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - run: mkdir artifacts
      - uses: actions/download-artifact@v2
        with:
          name: libs
          path: artifacts

      - name: Install commitstat
        run: curl https://raw.githubusercontent.com/dropseed/commitstat/master/install.sh | bash -s -- -b $HOME/bin
      - name: Run commitstat
        run: |
          stat --format %s artifacts/libcls_ffi.so            | $HOME/bin/commitstat - --name libcls_ffi.so
          stat --format %s artifacts/libcls_ffi_aarch64.so    | $HOME/bin/commitstat - --name libcls_ffi_aarch64.so
          stat --format %s artifacts/libcls_ffi.dylib         | $HOME/bin/commitstat - --name libcls_ffi.dylib
          stat --format %s artifacts/cls_ffi.dll              | $HOME/bin/commitstat - --name cls_ffi.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${GITHUB_REF##*/} artifacts/* --repo $GITHUB_REPOSITORY
